/* Avanti: download every product photo the new site still needs, through your browser.
 *
 * WHY: avantiprint.com.au blocks scripted downloads and image hotlinking, so the new site
 * cannot load photos from it. Your logged-in browser can.
 *
 * HOW:
 *   1. Open https://avantiprint.com.au in Chrome and let it load.
 *   2. Open the console (Option + Command + J on Mac, Ctrl + Shift + J on Windows).
 *   3. Paste this whole file and press Enter.
 *   4. Click "Allow" if Chrome asks about downloading multiple files.
 *   5. Zip the downloaded images and send them over (they go in assets/products/).
 *
 * Or skip all this: whoever has cPanel/FTP can zip the files listed in
 * images-to-download.txt straight from wp-content/uploads.
 */
(async () => {
  const URLS = [
  "https://avantiprint.com.au/wp-content/uploads/2020/07/colors1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/1-copy-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/1-copy.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/A1-stadard.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/A2-stadard.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/A3-stadard.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/A4-stadard.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/A5-stadard.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/A6-stadard.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/A7-stadard.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/A8-stadard.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/A9-stadard.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Age-Topper.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/AnniversaryTopper.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/BridetobeTopper.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/BridetobeTopper2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-1-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-10-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-10-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-10.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-11-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-11.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-12-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-12-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-12-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-12.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-13-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-13-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-13.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-14-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-14-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-14.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-15-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-15-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-15.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-16-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-16-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-16.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-17-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-17.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-18-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-18.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-19-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-19.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-2-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-20-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-20.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-21-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-21.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-22-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-22.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-23.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-3-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-3-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-4-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-4-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-4.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-5-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-5-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-5.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-6-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-6-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-7-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-7.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-8-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-8-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-8.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-9-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-9-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Close-Up-Design-9.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Communion-Cross-with-Name1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Complete-Wall-Design-13.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Complete-Wall-Design-14.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Complete-Wall-Design-15-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Complete-Wall-Design-15.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Complete-Wall-Design-8-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/CrossTopper1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Group-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/HAppy-bday-name-with-age.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Happy-birthday.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Happy-birthday2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Love-With-Arrow1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Name-Age1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Name-Ring1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Name-Topper.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Name-age3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Name-age4.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Name-age6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Name-age7.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Name-ring2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/NamewithCrossTopper.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Oh-Baby-Wreath1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-1-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-10-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-10-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-10.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-11-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-11-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-11.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-12-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-12-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-12.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-13-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-13-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-13-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-14-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-14-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-15-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-15-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-16-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-16-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-16.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-17-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-17.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-18-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-18.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-19-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-19.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-2-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-20-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-20.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-21-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-21.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-22-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-22.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-23.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-3-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-3-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-4-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-4-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-4.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-5-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-5-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-5.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-6-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-6-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-7-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-7-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-7.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-8-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-8.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-9-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-9-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Original-Artboard-Design-9.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/Twinkle-Twinkle-Little-Star1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/happy-21-liam.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/twenty-one.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/twenty-one1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/x.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A1-premium-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A1-premium.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A1-stadard-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A2-premium-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A2-premium.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A2-stadard-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A3-premium-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A3-premium.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A3-stadard-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A4-premium-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A4-premium.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A4-stadard-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A5-premium-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A5-premium.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A5-stadard-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A6-premium-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A6-premium.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A6-stadard-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A7-premium-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A7-premium.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A7-stadard-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A8-premium-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A8-premium.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A8-stadard-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A9-premium-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A9-premium.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/A9-stadard-ds.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/avanti-pullup-banner-design1-mockup.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/avanti-pullup-banner-design2-mockup.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/05/avanti-pullup-banner-design3-mockup.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/06/mailer-boxes-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/06/mailer-boxes-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/06/mailer-boxes-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/06/shipping-cartoon-image-new.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/07/blank-cartoon-box.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/07/mailer-boxes-blank.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/A-frame-02.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/A-frame-03.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/A-frame-5.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/A-frame-6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/A-frame-fetured-img.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/A-frame4.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/Acm-02.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/Acm-03.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/Acm-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/Acm-4.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/Acm-5.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/Acm-6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/Acm-7.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/corflute-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/corflute-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/corflute-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/corflute-4.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/corflute-5.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/corflute-6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/enviro-board-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/enviro-board2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/enviroboard-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/enviroboard-4.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/enviroboard-5.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/enviroboard-6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/floor-decals-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/floor-decols-4.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/floor-decols.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/floor-decols2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/floor-decols5.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/floor-decols6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/foam-board-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/foam-board-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/foam-board-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/foam-board-4.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/foam-board-5.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/foam-board-6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/posters-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/posters-3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/posters-5.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/posters-6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/pvc-2.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/pvc-foam-1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/pvc3.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/pvc4.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/pvc5.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/pvc6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/window-grahic-4.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/window-graphics-6.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/window-graphics1.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/10/window-graphics5.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2026/05/How-Do-Custom-Pull-Up-Banners-Transform-Local-Visibility-Into-Real-World-Impact.png",
  "https://avantiprint.com.au/wp-content/uploads/2026/06/EOFY-sale-signage-including-a-pull-up-banner-and-A-frame.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2026/07/Custom-branded-mailer-box-being-opened-showing-a-considered-unboxing-experience.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2026/08/Pull-Up-Banners-That-Actually-Get-Read-Most-Dont.jpg",
  "https://avantiprint.com.au/wp-content/uploads/2025/04/avanti-custom.jpg"
  ];
  if (!location.hostname.endsWith("avantiprint.com.au")) { console.error("Run this on an avantiprint.com.au page"); return; }
  let ok = 0; const failed = [];
  for (const url of URLS) {
    const name = url.split("/").pop();
    try {
      const res = await fetch(url, { credentials: "include" });
      if (!res.ok) { failed.push(name + " (HTTP " + res.status + ")"); continue; }
      const blob = await res.blob();
      if (!blob.type.startsWith("image/")) { failed.push(name + " (not an image)"); continue; }
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob); a.download = name;
      document.body.appendChild(a); a.click(); a.remove();
      setTimeout(() => URL.revokeObjectURL(a.href), 4000);
      ok++; console.log("\u2713 " + name);
      await new Promise(r => setTimeout(r, 500));
    } catch (e) { failed.push(name + " (" + e.message + ")"); }
  }
  console.log("Downloaded " + ok + " of " + URLS.length);
  if (failed.length) { console.log("Failed:"); failed.forEach(f => console.log("  - " + f)); }
})();
